/* Browser acceptance through ordinary controls. Serve the repository root.
 * BASE_URL may point at the published app; no engine/internal state is accessed.
 * Requires Playwright. BROWSER_CHANNEL=chrome uses an installed Chrome.
 */
const assert=require('node:assert/strict'), fs=require('node:fs/promises'), path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BASE_URL||'http://127.0.0.1:8767/apps/semantic-tunnel-planner/';
const out=process.env.BROWSER_OUTPUT||'/tmp/solway-game-local-checks';
const checks=[],errors=[];
const note=(label,evidence)=>{checks.push({label,evidence});console.log('PASS '+label);};
(async()=>{await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});try{
const context=await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:'reduce',acceptDownloads:true});
const page=await context.newPage();const watch=p=>{p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error'&&!/favicon|fonts\.googleapis|fonts\.gstatic/.test(m.location().url||m.text()))errors.push(m.text());});};watch(page);
const hud=async()=>{const v=await page.locator('#hud .stat-value').allTextContents(),n=await page.locator('#hud .stat-note').allTextContents();return {hours:Number(v[0].split('/')[0].trim()),timeLimit:Number(v[0].match(/\/\s*(\d+)/)[1]),remainingBudget:Number(v[1].replace(/[^\d-]/g,'')),cost:Number(n[1].match(/£([\d,]+)/)[1].replaceAll(',','')),conditions:v[2],status:v[3],actions:Number(n[3].match(/\d+/)[0])};};
const fresh=async mission=>{await page.locator('#mission-'+mission).click();const h=await hud();assert.equal(h.hours,0);assert.equal(h.cost,0);assert.equal(h.actions,0);assert.equal(h.status,'Your move');return h;};
const board=()=>page.locator('#world').innerText();
const choose=async id=>{await page.locator('#card-'+id).click();};
const action=async id=>{await choose(id);const before=await hud(),resource=await page.locator('#card-'+id+' .resource').innerText();const duration=Number(resource.match(/(\d+) h/)[1]),cost=Number(resource.match(/£([\d,]+)/)[1].replaceAll(',',''));assert.ok(await page.locator('#dispatch-crew').isEnabled(),`${id}: ${(await page.locator('#crew-briefing').innerText())}`);await page.locator('#dispatch-crew').click();let h=await hud();assert.equal(h.cost,before.cost+cost,`${id} cost charged exactly once`);assert.equal(h.hours,before.hours,`${id} dispatch must not advance hours`);for(let i=0;i<duration;i++){if((await hud()).status==='Shift stopped')break;await page.locator('#tick').click();}return hud();};
const event=async id=>{const before=await hud();const text=await page.locator('#event-'+id).innerText();const hours=Number(text.match(/\+(\d+) h/)?.[1]||0),cost=Number((text.match(/£([\d,]+)/)?.[1]||'0').replaceAll(',',''));await page.locator('#event-'+id).click();const after=await hud();assert.equal(after.hours,before.hours+hours);assert.equal(after.cost,before.cost+cost);return after;};
const answer=async id=>{const before=await hud(),world=await board();await page.locator('#answer-'+id).click();assert.deepEqual(await hud(),before);assert.equal(await board(),world);assert.ok(await page.locator('#learning-card .feedback').isVisible());};
const win=async(expectedHours,expectedCost,goals=5)=>{const h=await hud();assert.equal(h.status,'Handed over');assert.equal(h.hours,expectedHours);assert.equal(h.cost,expectedCost);assert.equal(h.conditions,`${goals} / ${goals}`);assert.equal(await page.locator('#obligations .goal.met').count(),goals);assert.match(await board(),/Installed\. Accepted\. Temporary access cleared/);assert.match(await page.locator('#outcome').innerText(),/clean handover/i);assert.equal(await page.locator('#tick').count(),0);return h;};
const noOverflow=async()=>{const r=await page.evaluate(()=>({width:innerWidth,page:document.documentElement.scrollWidth,body:document.body.scrollWidth}));assert.ok(r.page<=r.width+1&&r.body<=r.width+1,JSON.stringify(r));return r;};
await page.goto(base,{waitUntil:'networkidle'});await page.locator('#mission-first-possession').waitFor();assert.equal(await page.locator('.mission-choice').count(),3);note('Three missions load and the first brief starts cleanly',await fresh('first-possession'));note('Desktop has no horizontal overflow',await noOverflow());await page.screenshot({path:path.join(out,'desktop-initial.png'),fullPage:true});
await choose('gantry-install-a');const blocked=await page.locator('#crew-briefing').innerText();assert.ok(await page.locator('#dispatch-crew').isDisabled());assert.match(blocked,/Requires shared gantry available/);assert.equal((await hud()).cost,0);note('Blocked installation explains the missing prerequisite without charging resources',blocked);
await action('gantry-setup');assert.equal((await hud()).conditions,'0 / 5');assert.match(await board(),/Temporary access on site/i);assert.equal((await hud()).status,'Decision time');await choose('gantry-install-a');assert.ok(await page.locator('#dispatch-crew').isDisabled());note('Setup enables access but neither installs nor accepts a unit; pending decision blocks dispatch',await hud());
await event('planned-hour');await page.locator('#undo').click();assert.equal((await hud()).hours,2);assert.equal((await hud()).cost,300);assert.equal((await hud()).status,'Decision time');await event('overlap-crew');assert.equal((await hud()).cost,420);await page.locator('#undo').click();assert.equal((await hud()).cost,300);assert.equal((await hud()).status,'Decision time');await event('planned-hour');note('Undo restores a pending event and reverses both time and paid-choice consequences');await answer('record');assert.match(await page.locator('#learning-card').innerText(),/Yes\./);await page.screenshot({path:path.join(out,'desktop-gantry-ready.png'),fullPage:true});
await action('gantry-install-a');await answer('remaining-use');await action('gantry-install-b');assert.equal((await hud()).conditions,'2 / 5');assert.notEqual((await hud()).status,'Handed over');note('Two installed units are insufficient without inspection evidence and clearance',await hud());
await action('gantry-inspect-a');await answer('absence');await action('gantry-inspect-b');assert.equal((await hud()).conditions,'4 / 5');assert.notEqual((await hud()).status,'Handed over');note('Inspection evidence still leaves temporary clearance outstanding',await hud());await action('gantry-remove');note('First mission completes at the exact displayed time/cost with all three learning answers',await win(12,1120));assert.match(await page.locator('#outcome').innerText(),/3 \/ 3 learning questions/);await page.screenshot({path:path.join(out,'desktop-first-win.png'),fullPage:true});
await page.locator('#undo').click();let h=await hud();assert.equal(h.hours,11);assert.equal(h.cost,1000);assert.equal(h.conditions,'4 / 5');assert.match(await board(),/Temporary access on site/i);note('Undo rewinds the entire last clearance decision and its resource effects',h);
await page.locator('#restart').click();assert.equal((await hud()).actions,0);assert.equal((await hud()).cost,0);assert.equal(await page.locator('#learning-card .feedback').count(),0);note('Restart clears prior actions, charges and learning state');
await action('gantry-setup');await event('planned-hour');await answer('installed');assert.match(await page.locator('#learning-card').innerText(),/useful distinction/i);assert.equal(await page.locator('#answer-record').count(),0);note('A wrong first learning answer gives explanatory feedback without changing the world',await hud());
await fresh('first-possession');await page.locator('#method-trolley').click();await action('trolley-setup-a');await event('planned-hour');await action('trolley-install-a');await action('trolley-inspect-a');await action('trolley-remove-a');await action('trolley-setup-b');await action('trolley-install-b');await action('trolley-inspect-b');await action('trolley-remove-b');note('The alternate trolley method completes both units through eight work actions',await win(15,1040));assert.equal((await hud()).actions,8);
await answer('record');await page.locator('#next-question').click();await answer('remaining-use');await page.locator('#next-question').click();await answer('absence');assert.equal((await hud()).status,'Handed over');assert.match(await page.locator('#outcome').innerText(),/3 \/ 3 learning questions/);note('All unanswered learning questions remain reachable after physical completion');
await fresh('first-possession');await action('gantry-setup');await event('planned-hour');await choose('gantry-remove');assert.match(await page.locator('#crew-briefing').innerText(),/still installation or inspection|Early removal/);await action('gantry-remove');await choose('gantry-install-a');assert.ok(await page.locator('#dispatch-crew').isDisabled());await action('gantry-setup');for(const id of ['gantry-install-a','gantry-install-b','gantry-inspect-a','gantry-inspect-b','gantry-remove'])await action(id);note('Early removal is recoverable through paid re-setup and a valid final handover',await win(15,1540));
await fresh('tight-possession');await page.locator('#method-trolley').click();await choose('trolley-setup-a');assert.ok(await page.locator('#dispatch-crew').isDisabled());assert.match(await page.locator('#crew-briefing').innerText(),/trolley permitted/);await page.locator('#method-gantry').click();await action('gantry-setup');await event('planned-hour');for(const id of ['gantry-install-a','gantry-install-b','gantry-inspect-a'])await action(id);assert.match(await page.locator('#shift-event').innerText(),/acceptance record/);await event('prepared-pack');await action('gantry-inspect-b');await action('gantry-remove');note('Tight mission wins using free crew handover and paid record pack',await win(12,1210));
await fresh('tight-possession');await action('gantry-setup');await event('overlap-crew');for(const id of ['gantry-install-a','gantry-install-b','gantry-inspect-a'])await action(id);await event('planned-hour');await action('gantry-inspect-b');await action('gantry-remove');note('Tight mission also wins using paid overlap crew and free record hour',await win(12,1240));
await fresh('tight-possession');await action('gantry-setup');await event('planned-hour');for(const id of ['gantry-install-a','gantry-install-b','gantry-inspect-a'])await action(id);await event('planned-hour');await action('gantry-inspect-b');h=await hud();assert.equal(h.status,'Shift stopped');assert.equal(h.hours,12);assert.equal(h.conditions,'4 / 5');assert.match(await page.locator('#outcome').innerText(),/window has ended/);assert.equal(await page.locator('#tick').count(),0);note('Both free handover hours fail the tight window before site clearance',h);await page.screenshot({path:path.join(out,'desktop-time-failure.png'),fullPage:true});await page.locator('#undo').click();assert.notEqual((await hud()).status,'Shift stopped');note('Undo recovers a failed run to its preceding decision boundary');
await fresh('tight-possession');await action('gantry-setup');await event('overlap-crew');for(const id of ['gantry-install-a','gantry-install-b','gantry-inspect-a'])await action(id);await event('prepared-pack');await action('gantry-inspect-b');await action('gantry-remove');h=await hud();assert.equal(h.status,'Shift stopped');assert.equal(h.cost,1330);assert.match(await page.locator('#outcome').innerText(),/budget has been exceeded/);assert.equal(await page.locator('#tick').count(),0);note('Both paid handovers fail the tight budget with explicit feedback',h);
await fresh('small-scope');assert.equal(await page.locator('#obligations .goal').count(),3);assert.equal(await page.locator('#work-cards [id$="-b"]').count(),0);await action('gantry-setup');await event('planned-hour');for(const id of ['gantry-install-a','gantry-inspect-a','gantry-remove'])await action(id);note('Reduced scope retains one shared setup/removal and completes only A',await win(8,770,3));assert.equal((await hud()).actions,4);
await fresh('first-possession');await choose('gantry-setup');await page.locator('#dispatch-crew').click();await page.locator('#tick').click();const savedHud=await hud(),savedClock=await page.locator('#work-clock').innerText();await page.reload({waitUntil:'networkidle'});assert.deepEqual(await hud(),savedHud);assert.equal(await page.locator('#work-clock').innerText(),savedClock);assert.match(await page.locator('#notice').innerText(),/restored.*paused/);await page.waitForTimeout(950);assert.deepEqual(await hud(),savedHud);note('Automatic browser restore retains in-progress work and pauses the clock',savedHud);
await page.locator('.shift-log > summary').click();const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export').click()]);const savePath=path.join(out,download.suggestedFilename());await download.saveAs(savePath);const save=JSON.parse(await fs.readFile(savePath,'utf8'));assert.ok(Array.isArray(save.commands));assert.ok(!('facts' in save));await page.locator('#restart').click();await page.locator('#import').setInputFiles(savePath);await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('replayed successfully'));assert.deepEqual(await hud(),savedHud);assert.match(await page.locator('#save-status').innerText(),/replayed successfully/);note('Save download and import replay decisions without importing completion flags',{filename:download.suggestedFilename(),commands:save.commands});
const badPath=path.join(out,'invalid-shift.json');await fs.writeFile(badPath,JSON.stringify({...save,facts:['installed-a']}));await page.locator('#import').setInputFiles(badPath);await page.waitForFunction(()=>/rejected|unexpected fields/.test(document.querySelector('#save-status').textContent));assert.match(await page.locator('#save-status').innerText(),/rejected|unexpected fields/);assert.deepEqual(await hud(),savedHud);note('Invalid saved state is rejected while the current shift remains intact');
await page.locator('#undo').click();assert.equal((await hud()).cost,0);assert.equal((await hud()).hours,0);await page.locator('#help-toggle').focus();await page.keyboard.press('Enter');assert.ok(await page.locator('#help').isVisible());await page.keyboard.press('Enter');assert.ok(await page.locator('#help').isHidden());note('Keyboard activation opens and closes the gameplay help');
await page.setViewportSize({width:390,height:844});await fresh('first-possession');note('Mobile initial game fits without horizontal overflow',await noOverflow());await page.screenshot({path:path.join(out,'mobile-initial.png'),fullPage:true});await page.locator('#card-gantry-setup').focus();await page.keyboard.press('Enter');await page.locator('#dispatch-crew').focus();await page.keyboard.press('Enter');await page.locator('#tick').click();await page.locator('#tick').click();note('Mobile keyboard dispatch and manual clock reach the first decision',await noOverflow());await page.screenshot({path:path.join(out,'mobile-decision.png'),fullPage:true});await event('planned-hour');await answer('record');note('Mobile decision and learning feedback fit without horizontal overflow',await noOverflow());await page.locator('#learning').screenshot({path:path.join(out,'mobile-learning.png')});await page.locator('#dispatch').screenshot({path:path.join(out,'mobile-workbench.png')});
for(const id of ['gantry-install-a','gantry-install-b','gantry-inspect-a','gantry-inspect-b','gantry-remove'])await action(id);note('A complete mission also works through the mobile layout',{outcome:await win(12,1120),layout:await noOverflow()});await page.screenshot({path:path.join(out,'mobile-first-win.png'),fullPage:true});
const autoContext=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'no-preference'}),autoPage=await autoContext.newPage();watch(autoPage);await autoPage.goto(base,{waitUntil:'networkidle'});await autoPage.locator('#card-gantry-setup').click();await autoPage.locator('#dispatch-crew').click();await autoPage.waitForFunction(()=>document.querySelector('#work-clock')?.innerText.includes('1 / 2 h'),null,{timeout:5000});await autoPage.locator('#pause').click();const paused=await autoPage.locator('#hud').innerText();await autoPage.waitForTimeout(1000);assert.equal(await autoPage.locator('#hud').innerText(),paused);await autoPage.locator('#pause').click();await autoPage.locator('#event-planned-hour').waitFor({timeout:5000});note('Normal-motion autoplay advances work; Pause stops time and Continue resumes');await autoContext.close();
assert.deepEqual(errors,[]);note('No application JavaScript or console errors');await fs.writeFile(path.join(out,'browser-receipt.json'),JSON.stringify({base,checkedAt:new Date().toISOString(),checks,errors},null,2)+'\n');console.log(`Verified ${checks.length} ordinary-interface checks. Evidence: ${out}`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
