(function () {
  'use strict';
  const G = globalThis.TunnelGame, $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = n => `£${Number(n).toLocaleString('en-GB')}`, STORE = 'solway-handover-game-v1';
  const names = {'first-possession':'The first handover','tight-possession':'Beat the possession window','small-scope':'A smaller brief'};
  const lessons = {'first-possession':'Learn the site, choose a method, leave it ready.','tight-possession':'Trade time and money without losing the goal.','small-scope':'Remove Unit B. Discover what work still matters.'};
  let state = G.create('first-possession'), selected = 'gantry-setup', method = 'gantry', auto = false, timer = null, uiNotice = '', storageAvailable = true;
  try {const saved=localStorage.getItem(STORE);if(saved){const restored=G.restore(saved);if(G.view(restored).status!=='invalid'){state=restored;uiNotice='Your last shift is restored. Any work in progress is paused.';}else uiNotice='The previous save could not be restored. A fresh mission is ready.';}}catch(_){storageAvailable=false;}
  function save(){if(!storageAvailable)return;try{localStorage.setItem(STORE,G.serialize(state));}catch(_){storageAvailable=false;}}
  function timerSync(v){if(timer){clearInterval(timer);timer=null;}if(auto&&v.active&&v.status==='playing'&&!document.hidden)timer=setInterval(()=>update(G.tick(state)),800);}
  function update(next,note=''){state=next;uiNotice=note;save();render();}
  function configLink(v,view='reasons'){const c=v.mission.config;return `../work-that-must-exist/index.html#scope=${c.scope}&access=${c.access}&methods=${c.methods}&view=${view}`;}
  function physicalText(v){
    const units=v.mission.config.scope==='both'?['a','b']:['a'],installed=units.filter(u=>v.facts.includes(`installed-${u}`)).length,evidence=units.filter(u=>v.facts.includes(`evidence-${u}`)).length;
    const clear=!v.facts.some(f=>['gantry-present','trolley-a-present','trolley-b-present'].includes(f));
    if(v.status==='complete')return 'Installed. Accepted. Temporary access cleared. The site is ready to hand over.';
    if(v.status==='failed')return v.active?'The shift has stopped. The dispatched work has not finished; its effects do not hold.':'The shift has stopped without an on-time, within-budget handover. Undo a decision or try again.';
    if(v.active)return `${v.active.label} — the crew is working; the result takes effect when the job finishes.`;
    if(!installed)return clear?'The units are at the workface. Choose how the crews will reach them.':'Temporary access is in place. The installation crew can now use it.';
    if(evidence<units.length)return `${installed} of ${units.length} units installed; ${evidence} inspection record${evidence===1?'':'s'}. Keep access available for the remaining inspections.`;
    return clear?'The physical handover conditions hold. Check the shift outcome.':'The inspection records are ready. Temporary access still has to leave.';
  }
  function world(v){
    const has=x=>v.facts.includes(x),gantry=has('gantry-present'),clear=!gantry&&!has('trolley-a-present')&&!has('trolley-b-present');
    const unit=(id,x,color)=>{const scoped=v.mission.config.scope==='both'||id==='a',installed=has(`installed-${id}`),evidence=has(`evidence-${id}`),trolley=has(`trolley-${id}-present`);
      return `<g opacity="${scoped?1:.28}"><text x="${x}" y="89" text-anchor="middle" fill="${color}" font-size="16" font-weight="600">UNIT ${id.toUpperCase()}</text><rect x="${x-42}" y="110" width="84" height="82" rx="4" fill="${installed?color:'#183b45'}" fill-opacity="${installed?.85:.25}" stroke="${color}" stroke-width="2" ${installed?'':'stroke-dasharray="5 5"'}/>${[0,1,2,3].map(i=>`<path d="M${x-26},${126+i*15}h52" stroke="${installed?'#17343e':color}" opacity=".45"/>`).join('')}<text x="${x}" y="217" text-anchor="middle" fill="#d9e8df" font-size="12">${!scoped?'Not in this brief':installed?'Installed':'Awaiting installation'}</text><g transform="translate(${x-60},236)"><rect width="120" height="29" rx="4" fill="${evidence?'#c8e4e0':'#203e48'}" stroke="${evidence?'#a9d9d6':'#45636b'}"/><text x="60" y="19" text-anchor="middle" fill="${evidence?'#174750':'#96b1b9'}" font-size="10">${evidence?'✓ Inspection record':scoped?'Record still needed':'No work requested'}</text></g>${trolley?`<g stroke="#edb965" stroke-width="3" fill="none"><path d="M${x-54},176v58h108v-58M${x-54},183h108"/><circle cx="${x-36}" cy="241" r="5"/><circle cx="${x+36}" cy="241" r="5"/></g>`:''}</g>`;};
    return `<div class="world-head"><span>Schematic · two-unit tunnel fit-out</span><span class="${clear?'clear':'occupied'}">${clear?'Access clear':'Temporary access on site'}</span></div><svg viewBox="0 0 720 296" role="img" aria-label="${esc(physicalText(v))}"><defs><pattern id="site-grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="#2d4d55" stroke-width=".4"/></pattern></defs><rect width="720" height="296" fill="url(#site-grid)"/><path d="M40 268V116Q40 40 134 40H586Q680 40 680 116V268" fill="none" stroke="#486973" stroke-width="2"/><path d="M20 276H700" stroke="#71908d" stroke-width="2"/>${unit('a',225,'#6bc6b6')}${unit('b',495,'#87b2e8')}${gantry?'<g stroke="#edb965" fill="none" stroke-width="4"><path d="M133 270V58H587V270M133 70H587"/><path d="M133 58L164 70L196 58L228 70L260 58L292 70L324 58L356 70L388 58L420 70L452 58L484 70L516 58L548 70L587 58" stroke-width="1.2"/><path d="M360 70v31l-10 8" stroke-width="2"/><circle cx="133" cy="272" r="5" fill="#edb965"/><circle cx="587" cy="272" r="5" fill="#edb965"/></g><rect x="282" y="19" width="156" height="23" rx="3" fill="#edb965"/><text x="360" y="35" fill="#493919" text-anchor="middle" font-size="11">ONE SHARED GANTRY</text>':''}${v.active&&v.status==='playing'?'<g class="working-glow" fill="#edb965"><circle cx="358" cy="242" r="6"/><path d="M353 250h10l4 19h-18z"/><rect x="350" y="240" width="16" height="3"/></g>':''}</svg><div class="world-caption">${esc(physicalText(v))}</div>`;
  }
  function meaning(a){
    const u=a.unit?`Unit ${a.unit}`:'the requested units';
    if(a.kind==='enable')return {title:'A means, not a deliverable',text:a.method==='gantry'?'One shared gantry can support both units. Setting it up changes what the crews can do; it does not install a unit or produce acceptance evidence.':'This trolley gives access to one unit. The other unit needs its own trolley setup. The same required function can have a different method.',changes:'Temporary access becomes available.',sector:'Plan the access before sending the installation crew. It will also be needed for inspection.'};
    if(a.kind==='install')return {title:'A process changes the product',text:`Installation changes ${u} from available-at-workface to installed. That is a physical result. Acceptance evidence is a separate obligation.`,changes:`${u} becomes installed.`,sector:'Keep suitable temporary access available for the inspection crew, even after installation finishes.'};
    if(a.kind==='inspect')return {title:'Evidence makes acceptance inspectable',text:`In this model, a successful inspection creates the record for ${u}. The record is information about the product, not another piece of the product.`,changes:`An inspection record for ${u} becomes present.`,sector:'The inspector uses the same temporary access as installation. Inspection failure and rework are outside this particular model.'};
    return {title:'Absence can be a completion condition',text:'Removing temporary access adds no permanent product. It still belongs in the work plan because the site must be returned clear.',changes:a.method==='gantry'?'The shared gantry is removed.':`The trolley for ${u} is removed.`,sector:'Check the remaining installation and inspection needs first. Early removal is allowed, but setting up again costs more.'};
  }
  function shortLabel(a){if(a.kind==='enable')return a.method==='gantry'?'Set up the gantry':`Trolley for Unit ${a.unit}`;if(a.kind==='remove')return a.method==='gantry'?'Remove the gantry':`Remove trolley ${a.unit}`;return `${a.kind==='install'?'Install':'Inspect'} Unit ${a.unit}`;}
  function render(){
    const focus=document.activeElement?.id,v=G.view(state);if(!v.mission){$('notice').textContent=v.reason;return;}
    const mid=v.mission.id,done=v.goals.filter(g=>g.satisfied).length;
    $('mission-picker').innerHTML=G.missions.map((m,i)=>`<button class="mission-choice" id="mission-${m.id}" data-mission="${m.id}" aria-pressed="${m.id===mid}"><span class="mission-number">0${i+1}</span><span><strong>${esc(names[m.id])}</strong><span class="description">${esc(lessons[m.id])}</span></span></button>`).join('');
    $('mission-kicker').textContent=`Mission ${G.missions.findIndex(m=>m.id===mid)+1} / 3 · Your shift`;$('shift-title').textContent=names[mid];$('undo').disabled=!v.canUndo;
    $('hud').innerHTML=[['Training time',`${v.hours} / ${v.timeLimit} h`,`${v.remainingHours} hours remaining`,v.remainingHours<3],['Training budget',money(v.remainingBudget),`${money(v.cost)} spent of ${money(v.budget)}`,v.remainingBudget<200],['Handover conditions',`${done} / ${v.goals.length}`,v.outcome.goalsMet?'All physical conditions hold':'A clear site alone is not a handover',false],['Shift status',v.status==='complete'?'Handed over':v.status==='failed'?'Shift stopped':v.event?'Decision time':v.active?'Crew working':'Your move',v.completedActions.length+' completed work actions',v.status==='failed']].map(([l,val,n,w])=>`<div class="stat ${w?'warn':''}"><div class="stat-label">${l}</div><div class="stat-value">${esc(val)}</div><div class="stat-note">${esc(n)}</div></div>`).join('');
    $('brief').innerHTML=`<p>${esc(v.mission.brief)}</p><div class="brief-tags"><span>${v.mission.config.scope==='both'?'Units A + B':'Unit A only'}</span><span>${v.mission.config.access==='tight'?'Tight access':'Open access'}</span><span>${v.mission.config.access==='tight'?'Gantry fits':'Both methods fit'}</span></div>`;
    $('obligations').innerHTML=v.goals.map(g=>`<div class="goal ${g.satisfied?'met':''}"><span class="goal-icon" aria-hidden="true">${g.satisfied?'✓':'·'}</span><span>${esc(g.label)}<span class="small"> — ${g.satisfied?'met':'still needed'}</span></span></div>`).join('');
    $('world').innerHTML=world(v);
    $('work-clock').innerHTML=v.active&&v.status==='playing'?`<div class="clock-label"><strong>${esc(v.active.label)}</strong> · ${v.active.duration-v.active.remaining} / ${v.active.duration} h<div class="clock-track"><i style="width:${(v.active.duration-v.active.remaining)/v.active.duration*100}%"></i></div></div><button id="pause" class="quiet">${auto?'Pause':'Continue'}</button><button id="tick" class="quiet">Advance 1 h</button>`:`<span class="small">${v.status==='playing'?'Time is paused while you think. Select work below to dispatch a crew.':v.status==='event'?'The crew is waiting for your handover decision.':'Your shift is paused.'}</span>`;
    const notice=uiNotice||(typeof v.notice==='string'?v.notice:v.notice?.text||v.notice?.message||'');
    $('notice').innerHTML=esc(notice)+(v.question&&!v.question.feedback?' <a class="question-ready" href="#learning">A learning question is ready ↓</a>':'');
    $('shift-event').innerHTML=v.event?`<p class="eyebrow">A decision on your shift</p><h3>${esc(v.event.title)}</h3><p>${esc(v.event.body)}</p><div class="event-choices">${v.event.choices.map(c=>`<button class="event-choice" id="event-${c.id}" data-choice="${c.id}"><strong>${esc(c.label)}</strong><span>${c.hours?`+${c.hours} h`:'No extra hours'} · ${c.cost?money(c.cost):'No extra cost'}</span><span class="small">${esc(c.reason)}</span></button>`).join('')}</div>`:'';
    const ended=['complete','failed','infeasible'].includes(v.status);$('outcome').className=`outcome ${v.status==='failed'?'failed':''}`;
    $('outcome').innerHTML=ended?`<p class="eyebrow">Shift debrief</p><h3>${v.status==='complete'?'A clean handover.':v.status==='failed'?'The window or budget got away.':'No route from this state.'}</h3><p>${esc(v.reason)}</p><p>${v.outcome.goalsMet?'The physical obligations all hold.':'Some handover obligations are still unmet.'} ${v.correctAnswers} / ${v.questionsTotal} learning questions answered correctly; learning scores are separate from handover.</p><div class="outcome-actions"><button id="retry" class="primary">${v.status==='complete'?'Play this mission again':'Try the mission again'}</button>${mid!=='small-scope'?`<button id="next-mission" data-mission="${G.missions[G.missions.findIndex(m=>m.id===mid)+1].id}">Next mission →</button>`:''}<a href="${configLink(v)}">Inspect this brief in the essay ↗</a></div>`:'';
    $('route-hint').textContent=v.remainingPlan.status==='solved'?`${v.remainingPlan.actionIds.length} actions in a shortest remaining route*`:'No remaining model route';
    if(!$('method-picker')){const d=document.createElement('div');d.id='method-picker';d.className='method-picker';d.setAttribute('role','group');d.setAttribute('aria-label','View access method');$('dispatch').insertBefore(d,$('dispatch').querySelector('.dispatch-grid'));}
    $('method-picker').innerHTML=`<button id="method-gantry" data-method="gantry" aria-pressed="${method==='gantry'}">Gantry · shared access</button><button id="method-trolley" data-method="trolley" aria-pressed="${method==='trolley'}">Trolleys · one per unit</button><span class="small">*Work actions only; the route count excludes game hours, costs and incidents.</span>`;
    const actions=v.actions.filter(a=>a.method===method&&(!a.unit||v.mission.config.scope==='both'||a.unit==='A'));
    if(!actions.some(a=>a.id===selected))selected=actions.find(a=>a.available)?.id||actions[0]?.id;
    $('work-cards').innerHTML=actions.map(a=>`<button id="card-${a.id}" class="work-card ${a.available?'':'blocked'} ${a.completedCount?'done':''} ${selected===a.id?'selected':''}" data-action="${a.id}" data-kind="${a.kind}" aria-pressed="${selected===a.id}"><span class="kind">${{enable:'Enable',install:'Product',inspect:'Evidence',remove:'Clearance'}[a.kind]}<span>${a.unit||'Shared'}</span></span><strong>${esc(shortLabel(a))}</strong><span class="resource">${a.duration} h · ${money(a.cost)}</span><span class="availability">${a.available?(a.completedCount?'Ready to repeat':'Ready to dispatch'):a.completedCount?'Used in this shift · inspect':'Not ready · inspect why'}</span></button>`).join('');
    const a=actions.find(x=>x.id===selected);
    if(a){const m=meaning(a),early=a.kind==='remove'&&v.goals.some(g=>g.unit&&!g.satisfied);$('crew-briefing').innerHTML=`<p class="eyebrow">Crew briefing</p><h3>${esc(a.label)}</h3><div class="crew-label">${esc(a.trade)} · ${a.duration} h · ${money(a.cost)}</div><p><strong>${m.title}</strong></p><p>${esc(m.text)}</p><p class="small">${esc(m.sector)}</p>${early?'<p class="caution">There is still installation or inspection work to do. Removing access now may mean paying to set it up again.</p>':''}${a.cost>v.remainingBudget||a.duration>v.remainingHours?'<p class="caution">This work would exceed the remaining training allowance. You can choose it and see the failed-shift result, or undo an earlier decision.</p>':''}${a.available?'<p class="small"><strong>Ready:</strong> the required facts hold.</p>':`<ul>${a.blockedReasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul>`}<button class="primary" id="dispatch-crew" ${a.available?'':'disabled'}>Dispatch crew →</button><details><summary>What does this action change?</summary><div class="facts"><p>${esc(m.changes)}</p><p><strong>Needs:</strong> ${a.positive.map(G.factLabel).map(esc).join('; ')}${a.negative.length?'; absent: '+a.negative.map(G.factLabel).map(esc).join('; '):''}.</p><p><strong>Adds:</strong> ${a.add.map(G.factLabel).map(esc).join('; ')||'No new fact'}.</p><p><strong>Removes:</strong> ${a.delete.map(G.factLabel).map(esc).join('; ')||'No fact'}.</p></div></details>`;}
    $('learning-progress').innerHTML=[0,1,2].map(i=>`<span class="learning-step ${v.questionsAnswered[i]?'done':''}" aria-label="Question ${i+1}${v.questionsAnswered[i]?', answered':''}">${i+1}</span>`).join('');
    const q=v.question;
    $('learning-card').innerHTML=q?`<p class="eyebrow">${q.id==='meaning'?'01 · Product and evidence':q.id==='shared'?'02 · Shared enabling work':'03 · The state you hand back'}</p><h3>${esc(q.prompt)}</h3>${q.feedback?`<div class="feedback ${q.feedback.correct?'':'incorrect'}"><strong>${q.feedback.correct?'Yes.':'A useful distinction.'}</strong> ${esc(q.options.find(o=>o.id===v.questionsAnswered.find(a=>a.questionId===q.id)?.optionId)?.explanation||q.feedback.text)}<p><strong>Project:</strong> ${esc(q.feedback.project)}</p><p><strong>Meaning:</strong> ${esc(q.feedback.semantics)}</p><p><strong>Tunnel work:</strong> ${esc(q.feedback.sector)}</p>${v.canNextQuestion?'<button id="next-question" class="quiet">Next learning question →</button>':''}</div>`:`<div class="learning-options">${q.options.map(o=>`<button class="learning-option" id="answer-${o.id}" data-answer="${o.id}">${esc(o.label)}</button>`).join('')}</div>`}`:`<p class="eyebrow">Learn through your decisions</p><h3>${v.questionsAnswered.length===3?'You have worked through all three distinctions.':'Your first distinction starts at the workface.'}</h3><p>${v.questionsAnswered.length===3?'Your score records first answers, not project completion. Use the shift log to connect each explanation to what happened.':'Set up access and the first question will appear here. More questions follow installation and inspection.'}</p>`;
    $('log-count').textContent=`· ${v.log.length} entries`;$('log').innerHTML=[...v.log].reverse().map(e=>`<div class="log-entry"><span class="stamp">${esc(e.hours??e.hour??'')}${e.hours!==undefined||e.hour!==undefined?' h':''}</span><span>${esc(typeof e==='string'?e:e.text||e.message||e.label||JSON.stringify(e))}</span></div>`).join('');
    $('meaning-link').href=configLink(v,'wbs');if(!storageAvailable)$('save-status').textContent='Browser storage is unavailable. Save this shift to a file if you want to keep it.';
    if(focus)document.getElementById(focus)?.focus({preventScroll:true});timerSync(v);
  }
  function restart(id){auto=false;selected='gantry-setup';method='gantry';update(G.create(id),'A fresh shift. Choose the work that gets you to handover.');}
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
    if(b.dataset.mission){restart(b.dataset.mission);return;}if(b.dataset.method){method=b.dataset.method;selected='';render();return;}if(b.dataset.action){selected=b.dataset.action;render();if(matchMedia('(max-width:760px)').matches)$('crew-briefing').scrollIntoView({block:'start',behavior:'smooth'});return;}if(b.dataset.choice){auto=false;update(G.resolveEvent(state,b.dataset.choice));return;}if(b.dataset.answer){update(G.answerQuestion(state,b.dataset.answer));return;}
    switch(b.id){case'next-question':update(G.nextQuestion(state));break;case'dispatch-crew':auto=!matchMedia('(prefers-reduced-motion: reduce)').matches;update(G.startAction(state,selected));break;case'pause':auto=!auto;render();break;case'tick':auto=false;update(G.tick(state));break;case'undo':auto=false;update(G.undo(state));break;case'restart':case'retry':restart(G.view(state).mission.id);break;case'help-toggle':$('help').hidden=!$('help').hidden;b.setAttribute('aria-expanded',String(!$('help').hidden));break;case'export':{const url=URL.createObjectURL(new Blob([G.serialize(state)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`solway-handover-${G.view(state).mission.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('save-status').textContent='Saved shift downloaded. Load it here to replay your decisions.';break;}}
  });
  $('import').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(f.size>30000){$('save-status').textContent='This file is too large for a saved shift.';e.target.value='';return;}try{const r=G.restore(await f.text()),v=G.view(r);if(v.status==='invalid'){$('save-status').textContent=v.reason;return;}auto=false;method='gantry';selected='';update(r,'Saved shift loaded; work is paused.');$('save-status').textContent='Saved decisions replayed successfully.';}catch(_){$('save-status').textContent='That saved shift could not be read.';}finally{e.target.value='';}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){auto=false;render();}});
  render();
})();
