(function () {
  'use strict';
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const presets = {both:{scope:'both',access:'open',methods:'both'},trolleys:{scope:'both',access:'open',methods:'trolley'},tight:{scope:'both',access:'tight',methods:'both'},one:{scope:'A',access:'tight',methods:'both'},blocked:{scope:'both',access:'tight',methods:'trolley'}};
  let config = {...presets.both}, result, comparison, selected = 0, step = 0, groupMode = 'product', activeTab = 'reasons', timer, meaningView = 'product', meaningSelection = '';
  const cache = new Map();
  const solve = c => {const key=JSON.stringify(c);if(!cache.has(key))cache.set(key,WorkModel.solve(c));return cache.get(key);};
  const scopeUnits = c => c.scope === 'both' ? ['A','B'] : c.scope === 'none' ? [] : [c.scope];
  const shortLabel = a => a.label.replace('the shared ', '').replace('from the gantry','').replace('from its trolley','').replace('Position a trolley for','Trolley for').replace('Remove the trolley for','Remove trolley for').trim();
  const goalName = id => result.obligations.find(x=>x.id===id)?.label || id;
  const actionName = id => result.problem?.actions.find(x=>x.id===id)?.label || id;
  function factName(fact, negative=false) {
    const words = {'gantry-present':'shared gantry present','trolley-a-present':'Unit A trolley present','trolley-b-present':'Unit B trolley present','allowed-gantry':'gantry permitted here','allowed-trolley':'trolley permitted here','installed-a':'Unit A installed','installed-b':'Unit B installed','evidence-a':'Unit A inspection recorded','evidence-b':'Unit B inspection recorded','requested-a':'Unit A requested','requested-b':'Unit B requested','unit-available-a':'Unit A available','unit-available-b':'Unit B available'};
    return negative ? `absence of ${words[fact]||fact}` : words[fact]||fact;
  }
  function stop(){clearInterval(timer);timer=null;$('play').textContent='Play route';}
  function writeURL(){const q=new URLSearchParams({...config,view:activeTab});history.replaceState(null,'',`#${q}`);}
  function readURL(){const q=new URLSearchParams(location.hash.slice(1));if(!q.has('scope'))return;try{config=WorkModel.normalizeConfig({scope:q.get('scope'),access:q.get('access'),methods:q.get('methods')});if(['reasons','wbs','comparison','findings'].includes(q.get('view')))activeTab=q.get('view');}catch{config={...presets.both};$('export-status').textContent='The saved settings were not recognised. The default experiment has been restored.';}}
  function controls(){const units=scopeUnits(config);$('unit-a').checked=units.includes('A');$('unit-b').checked=units.includes('B');$('access').value=config.access;$('methods').value=config.methods;document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(JSON.stringify(presets[b.dataset.preset])===JSON.stringify(config))));}
  function renderSummary(){
    const solved=result.status==='solved', unavoidable=(result.requiredFunctions||[]).filter(f=>f.unavoidable).length;
    const title=solved ? result.actions.length ? 'A completion route exists' : 'The goal is already satisfied' : 'No completion route in this model';
    $('result-summary').innerHTML=`<div class="summary-line"><div><span class="status-badge ${solved?'':'fail'}">${solved?'Generated and checked':'No viable method'}</span><br><strong>${title}</strong><p>${solved?'Fewest actions, with equal cost per action.':esc(result.reason)}</p></div><div class="stats"><div><b id="action-count">${solved?result.actions.length:'—'}</b><span>actions</span></div><div><b id="required-function-count">${solved?unavoidable:'—'}</b><span>required functions</span></div></div></div>`;
  }
  function renderScene(){
    const state=new Set(step?result.trace[step-1].after:result.problem?.initial||[]), units=scopeUnits(config), gantry=state.has('gantry-present');
    const clear=!['gantry-present','trolley-a-present','trolley-b-present'].some(x=>state.has(x));
    const parts=['<svg viewBox="0 0 820 240" role="img" aria-labelledby="scene-title scene-desc"><title id="scene-title">Tunnel fit-out at the selected step</title><desc id="scene-desc">'+esc(units.map(u=>`Unit ${u}: ${state.has(`installed-${u.toLowerCase()}`)?'installed':'not installed'}, ${state.has(`evidence-${u.toLowerCase()}`)?'inspection recorded':'no inspection record'}`).join('. ')+`. Temporary access ${clear?'absent':'present'}.`)+'</desc><defs><pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#ffffff" stroke-opacity=".045"/></pattern></defs><rect width="820" height="240" fill="url(#grid)"/><path d="M38 200V94Q38 35 104 35H716Q782 35 782 94V200" fill="none" stroke="#486471" stroke-width="2"/><path d="M28 201H792" stroke="#72918f" stroke-width="2"/><text x="40" y="24" fill="#adc1c5" font-size="13" font-family="Inter,Arial">SCHEMATIC / '+(step===0?'INITIAL STATE':`AFTER ACTION ${step}`)+'</text>'];
    for(const [i,u] of ['A','B'].entries()){
      const x=210+i*300,k=u.toLowerCase(),requested=units.includes(u),installed=state.has(`installed-${k}`),evidence=state.has(`evidence-${k}`),colour=u==='A'?'#45c0ac':'#73a5e9';
      parts.push(`<g opacity="${requested?1:.3}"><rect x="${x}" y="91" width="106" height="78" rx="5" fill="${installed?colour:'#142d38'}" fill-opacity="${installed?.22:1}" stroke="${colour}" stroke-width="2" ${installed?'':'stroke-dasharray="5 6"'}/><path d="M${x+18} 108h70m-70 13h70m-70 13h70m-70 13h70" stroke="${colour}" opacity="${installed?.7:.2}"/><text x="${x+53}" y="70" text-anchor="middle" fill="${colour}" font-size="18" font-family="Inter,Arial">UNIT ${u}</text><text x="${x+53}" y="222" text-anchor="middle" fill="#dbe9e6" font-size="14" font-family="Inter,Arial">${!requested?'Outside scope':evidence?'Installed · accepted':installed?'Installed · inspect next':'Awaiting installation'}</text></g>`);
      if(evidence)parts.push(`<circle cx="${x+102}" cy="94" r="12" fill="#45c0ac"/><path d="M${x+96} 94l4 4 8-9" stroke="#142d38" stroke-width="2" fill="none"/>`);
      if(state.has(`trolley-${k}-present`))parts.push(`<g stroke="#e9b358" stroke-width="3" fill="none"><path d="M${x-37} 186h54v-33h-39v33m0-24h38"/><circle cx="${x-23}" cy="194" r="6"/><circle cx="${x+12}" cy="194" r="6"/></g>`);
    }
    if(gantry)parts.push('<g stroke="#e9b358" fill="none" stroke-width="3"><path d="M130 197V80H686V197M130 175H686M158 80v95M658 80v95M130 151l28 24m528-24-28 24"/><path d="M145 80v-18h526v18" stroke-dasharray="5 4"/></g><rect x="334" y="167" width="150" height="21" fill="#142d38"/><text x="409" y="182" fill="#f0c16f" font-size="13" text-anchor="middle" font-family="Inter,Arial">SHARED GANTRY</text>');
    parts.push(`<text x="779" y="24" text-anchor="end" fill="${clear?'#a9caba':'#f0c16f'}" font-size="13" font-family="Inter,Arial">${clear?'TEMPORARY ACCESS CLEAR':'TEMPORARY ACCESS PRESENT'}</text></svg>`);
    $('scene').innerHTML=parts.join('');$('step-range').max=result.actions.length;$('step-range').value=step;$('step-range').disabled=!result.actions.length;$('step-label').textContent=`${step} / ${result.actions.length}`;
    $('step-back').disabled=step===0;$('step-next').disabled=step>=result.actions.length;$('play').disabled=!result.actions.length;
    $('scene-caption').textContent=step===0 ? units.length?'Initial state: units are available, uninstalled; temporary equipment is absent.':'No installation requested. The site begins clear, so no work is generated.' : `${result.trace[step-1].label}. ${step===result.actions.length?'All final obligations hold; temporary equipment is absent.':'The picture shows the resulting state.'}`;
  }
  function renderRoute(){
    if(!result.actions.length){$('route').innerHTML=`<p class="empty">${esc(result.reason)}</p>`;$('action-detail').innerHTML=result.status==='solved'?'<h3>No task list to preserve</h3><p>With no installation goal, search returns the empty route. Enabling work is not generated for its own sake.</p>':'<h3>A missing route is a result</h3><p>The model cannot manufacture an authorised method. Change access, restore a permissible method, or revise the goal.</p>';return;}
    $('route').innerHTML=result.actions.map((a,i)=>`<button class="action" data-action="${i}" data-action-id="${esc(a.id)}" data-unit="${a.unit||'shared'}" aria-pressed="${selected===i}"><span>${String(i+1).padStart(2,'0')} · ${a.unit?`Unit ${a.unit}`:'Shared'}</span><b>${esc(shortLabel(a))}</b></button>`).join('');
    $('route').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{stop();selected=+b.dataset.action;step=selected+1;renderRoute();renderScene();}));
    const a=result.actions[selected]||result.actions[0], n=a.necessity;
    const requirements=(a.supportedBy||[]).map(goalName);
    const pre=a.preconditions.map(x=>factName(x)), absent=a.negativePreconditions.map(x=>factName(x,true));
    $('action-detail').innerHTML=`<h3>${esc(a.label)}</h3><p><span class="pill ${n?.unavoidable?'required':'optional'}">${n?.unavoidable?'Unavoidable in this model':'Method-dependent'}</span> ${esc(n?.reason||'Necessity not tested.')}</p><p><strong>Supports:</strong> ${esc(requirements.join('; ')||'no final obligation')}.</p><details><summary>Preconditions and the alternative test</summary><p>Requires ${esc([...pre,...absent].join('; '))}.</p>${n?.alternativeActionIds?.length?`<p>A completion without this action:</p><ol>${n.alternativeActionIds.map(id=>`<li>${esc(actionName(id))}</li>`).join('')}</ol>`:'<p>No completion was found after forbidding this action; the finite search was exhausted.</p>'}</details>`;
  }
  function renderTakeaway(){
    let title,body;
    if(result.status!=='solved'){title='The goal has no route.';body='Access and permissions leave no usable method. A richer description cannot supply a missing capability.';}
    else if(config.scope==='none'){title='No goal, no invented work.';body='The site starts clear. With no units requested, the empty plan already satisfies the declared handover rule.';}
    else if(config.scope!=='both'){title='Shared work survives.';body=result.actions.some(a=>!a.unit)?`Removing the other unit leaves ${result.actions.length} actions. Shared gantry setup and removal remain because Unit ${config.scope} still needs them.`:`Only Unit ${config.scope} is requested. Its ${result.actions.length}-action trolley route needs no work for the other unit.`;}
    else if(config.access==='tight'||config.methods==='gantry'){title='A choice becomes a necessity.';body='The gantry route still has six actions. With no usable trolley alternative, forbidding any one of those actions prevents completion.';}
    else if(config.methods==='trolley'){title='Same outcome, different work.';body='Each unit needs its own trolley setup and removal. The generated route now has eight actions instead of six with a shared gantry.';}
    else{title='Necessary function, replaceable method.';body='The shortest route uses six actions. Every chosen gantry action can be avoided using another permitted route, but installation, inspection and temporary access still have to happen.';}
    $('experiment-takeaway').innerHTML=`<strong>${title}</strong><p>${body}</p>`;
  }
  function renderReasons(){
    const funcs=result.requiredFunctions||[];
    $('required-functions').innerHTML=funcs.length?`<h3>Functions that no route can avoid</h3><p class="measure">Forbid every method of performing one function and search again. These function groups come from the declared method descriptions; their necessity is computed.</p><div class="function-band">${funcs.map(f=>`<div><span>${f.unavoidable?'Required':'Replaceable'}</span><strong>${esc(f.label)}</strong></div>`).join('')}</div><p class="boundary">${result.actions.filter(a=>a.necessity?.unavoidable).length} of the ${result.actions.length} specific actions in this route are unavoidable. A required function can still have several methods.</p>`:result.status==='solved'?'<p class="empty">No installation functions are required when no units are requested.</p>':'<p class="empty">Function necessity is reported only for feasible briefs.</p>';

    const units=scopeUnits(config), groups=[...units.map(u=>({label:`Unit ${u} accepted`,class:`unit-${u}`,goals:result.obligations.filter(o=>o.unit===u)})),{label:'Site ready for handover',class:'site',goals:result.obligations.filter(o=>!o.unit)}];
    $('support-map').innerHTML=`<div class="support-grid">${groups.map(g=>{const ids=g.goals.map(o=>o.id),actions=result.actions.filter(a=>a.supportedBy.some(x=>ids.includes(x)));return `<article class="support-goal ${g.class}"><h3>${g.label}</h3><p>${g.goals.map(o=>esc(o.label)).join(' + ')}</p><ol>${actions.map(a=>`<li>${esc(shortLabel(a))}${a.supportedUnits?.length>1?'<small>shared by A and B</small>':''}</li>`).join('')||`<li>${g.goals.every(o=>o.satisfied)?'Satisfied in the initial state':'No generated support'}</li>`}</ol></article>`;}).join('')}</div><p class="boundary">Shared actions can appear under several outcomes here; they remain one action in the plan. Links show support in the chosen sequential route. Removal must also respect access-preservation ordering.</p>`;
    const before=solve({...config,scope:'both'});
    if(before.status!=='solved'||result.status!=='solved'){$('scope-delta').innerHTML='<p class="empty">A scope comparison needs a feasible reference and current route. Restore a usable method to inspect retained and removed work.</p>';return;}
    const delta=WorkModel.comparePlans(before,result);
    $('scope-delta').innerHTML=`<p><strong>${delta.beforeCount} → ${delta.afterCount} actions.</strong> ${config.scope==='both'?'Both units are still requested. Uncheck B to see what survives.':'Compared with delivering both units under these conditions.'}</p><ul class="delta-list">${delta.retained.map(a=>`<li><span class="kept">Retained</span>${esc(shortLabel(a))}</li>`).join('')}${delta.removed.map(a=>`<li><span class="removed">Removed</span>${esc(shortLabel(a))}</li>`).join('')}${delta.added.map(a=>`<li><span>Added</span>${esc(shortLabel(a))}</li>`).join('')}</ul>`;
  }
  function renderWBS(){
    renderMeaning();
    const p=WorkModel.packagePlan(result,groupMode), names=Object.fromEntries(p.packages.map(x=>[x.id,x.label]));
    $('group-product').setAttribute('aria-pressed',String(groupMode==='product'));$('group-trade').setAttribute('aria-pressed',String(groupMode==='trade'));
    $('wbs-summary').innerHTML=`<p><strong>${p.actionCount} actions · ${p.packages.length} packages · ${p.interfaces.length} cross-package links.</strong> ${esc(p.criterion)}</p>`;
    $('wbs').innerHTML=p.packages.map(g=>`<article class="package" data-package="${esc(g.id)}"><h3>${esc(g.label)}</h3><p class="boundary">Owner: ${esc(g.owner)}</p><ul>${g.actions.map(a=>`<li data-wbs-action="${esc(a.id)}">${esc(a.label)}<span>${a.supportedUnits.length?`Supports ${a.supportedUnits.map(u=>`Unit ${u}`).join(' and ')}`:'Supports site handover'}</span></li>`).join('')}</ul></article>`).join('')||'<p class="empty">No work packages are generated for this brief.</p>';
    const unique=[...new Map(p.interfaces.map(e=>[`${e.fromPackage}|${e.toPackage}|${e.fact}|${e.kind}`,e])).values()];
    $('interfaces').innerHTML=unique.length?`<h3>Interfaces preserved across the packages</h3><ul>${unique.map(e=>`<li><strong>${esc(names[e.fromPackage])} → ${esc(names[e.toPackage])}</strong>: ${esc(factName(e.fact,e.polarity==='negative'))}${e.kind==='protection'?' — preserve access until its consumer finishes':''}.</li>`).join('')}</ul><p class="boundary">These are fact-support and protection links, not durations or a resource-loaded schedule.</p>`:'';
  }
  function renderMeaning(){
    const unitItems=scopeUnits(config).map(unit=>({id:`product-${unit}`,label:`Unit ${unit}`,category:'Physical product',explanation:`Unit ${unit} is a requested physical installation. Its installed condition and its acceptance evidence are separate completion obligations.`,actions:result.actions.filter(a=>a.supportedUnits.includes(unit)),goals:result.obligations.filter(o=>o.unit===unit)}));
    const workItems=result.actions.map(a=>({id:a.id,label:a.label,category:'Proposed process',explanation:'This is one proposed process in the computed route. It contributes through its effects and causal support; its description is not a physical part of the installed unit.',actions:[a],goals:result.obligations.filter(o=>a.supportedBy.includes(o.id))}));
    const accessFacts=[...new Set(result.actions.filter(a=>a.kind==='enable').flatMap(a=>a.add))];
    const meansItems=accessFacts.map(fact=>({id:fact,label:factName(fact).replace(/ present$/,''),category:'Temporary physical means',explanation:'This equipment provides access during work. It must be absent at handover. Using equipment is different from making it part of the finished product.',actions:result.actions.filter(a=>[...a.positive,...a.negative,...a.add,...a.delete].includes(fact)),goals:result.obligations.filter(o=>o.negative.includes(fact))}));
    const evidenceItems=result.obligations.filter(o=>o.category==='InformationContent').map(o=>({id:o.id,label:o.label,category:'Information evidence',explanation:'An acceptance record is information about the installation. It is distinct from the physical unit and from the inspection process that produces it.',actions:result.actions.filter(a=>a.supportedBy.includes(o.id)),goals:[o]}));
    const collections={product:unitItems,work:workItems,means:meansItems,evidence:evidenceItems},items=collections[meaningView];
    if(!items.some(item=>item.id===meaningSelection))meaningSelection=items[0]?.id||'';
    document.querySelectorAll('[data-meaning-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.meaningView===meaningView)));
    $('meaning-map').innerHTML=items.length?`<div class="meaning-cards">${items.map(item=>`<button data-meaning-item="${esc(item.id)}" aria-pressed="${item.id===meaningSelection}"><small>${esc(item.category)}</small><strong>${esc(item.label)}</strong></button>`).join('')}</div>`:`<p class="empty">${result.status==='solved'?'This brief generates no items in this view.':'No feasible route was found, so no work or temporary means are proposed.'}</p>`;
    const item=items.find(x=>x.id===meaningSelection);
    if(!item){$('meaning-detail').innerHTML='';return;}
    const ids=new Set(item.actions.map(a=>a.id));
    const links=result.supports.filter(e=>meaningView==='work'?(ids.has(e.from)||ids.has(e.to)):(ids.has(e.from)&&(ids.has(e.to)||item.goals.some(o=>`goal:${o.id}`===e.to))));
    const nodeName=id=>id==='initial'?'Initial condition':id.startsWith('goal:')?goalName(id.slice(5)):actionName(id);
    $('meaning-detail').innerHTML=`<h3>${esc(item.label)}</h3><p>${esc(item.explanation)}</p><div class="meaning-columns"><div><h4>Work connected to this item</h4>${item.actions.length?`<ul>${item.actions.map(a=>`<li>${esc(a.label)}</li>`).join('')}</ul>`:`<p>${result.status==='solved'?'No work is needed.':'The obligation is declared, but no completion route exists.'}</p>`}</div><div><h4>Computed support</h4>${links.length?`<ul>${links.map(e=>`<li><strong>${esc(nodeName(e.from))}</strong> → ${esc(nodeName(e.to))}<small>Via ${esc(factName(e.fact,e.polarity==='negative'))}</small></li>`).join('')}</ul>`:'<p>No fact-support link is present in this route for this view.</p>'}</div></div>`;
    $('meaning-map').querySelectorAll('[data-meaning-item]').forEach(b=>b.addEventListener('click',()=>{meaningSelection=b.dataset.meaningItem;renderMeaning();}));
  }
  function renderComparison(){
    comparison=PDDL.compare(config,WorkModel.exportPDDL(config));
    const r=comparison, solved=result.status==='solved';
    // Check the displayed semantic route itself with the independent parser.
    const replay=PDDL.checkPlan(r.directPDDL.domain,r.directPDDL.problem,result.actions.map(a=>a.id));
    const parity=r.valid&&r.direct.found===solved&&(!solved||(r.direct.length===result.actions.length&&replay.valid));
    $('comparison').innerHTML=`<div class="comparison-verdict"><strong>${parity?'Planning parity for this brief':'The comparison found a mismatch'}</strong><p>${parity?solved?'Both independently searched problems reach the same final obligations in the same minimum number of actions.':'Both searches exhaust their finite state space without a completion route.':'The two representations or results differ. Inspect the exported models before drawing a conclusion.'}</p></div><table><thead><tr><th>Check</th><th>Semantic route</th><th>Direct PDDL</th></tr></thead><tbody><tr><th>Completion</th><td>${solved?'Achievable':'Unreachable'}</td><td>${r.direct.found?'Achievable':'Unreachable'}</td></tr><tr><th>Shortest action count</th><td>${solved?result.actions.length:'—'}</td><td>${r.direct.found?r.direct.length:'—'}</td></tr><tr><th>Final obligations</th><td>${result.obligations.length} declared</td><td>Same positive and negative goals</td></tr><tr><th>Actions, facts and goals match</th><td colspan="2">${r.sameSemantics?'Yes — compared by meaning, independent of action order':'No'}</td></tr><tr><th>Independent replay of displayed route</th><td colspan="2">${solved?(replay.valid?'Every precondition and final goal holds':'Failed'):'No successful route to replay'}</td></tr></tbody></table><details><summary>Compare the two generated action sequences</summary><div class="two-column"><div><strong>Semantic search</strong><ol>${result.actions.map(a=>`<li>${esc(a.label)}</li>`).join('')||'<li>No actions</li>'}</ol></div><div><strong>Direct PDDL search</strong><ol>${(r.direct.plan||[]).map(id=>`<li>${esc(actionName(id))}</li>`).join('')||'<li>No actions</li>'}</ol></div></div><p class="boundary">Different interleavings can have the same shortest length. Neither displayed sequence is claimed to be unique.</p></details>`;
    $('pddl-source').textContent=r.directPDDL.problem;
    $('semantic-obligations').innerHTML=`<table><thead><tr><th>Generated obligation</th><th>Meaning</th><th>Source rule</th></tr></thead><tbody>${result.obligations.map(o=>`<tr><td>${esc(o.label)}</td><td>${esc(o.category.replace('InformationContent','Information content'))}</td><td><code>d:${esc(o.source.split('#').pop())}</code></td></tr>`).join('')}</tbody></table>`;

  }
  function tab(name,focus=false){activeTab=name;document.querySelectorAll('[data-tab]').forEach(b=>{const on=b.dataset.tab===name;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;$(b.getAttribute('aria-controls')).hidden=!on;if(on&&focus)b.focus();});writeURL();}
  function render(){stop();controls();result=solve(config);step=0;selected=0;renderSummary();renderScene();renderRoute();renderTakeaway();renderReasons();renderWBS();renderComparison();tab(activeTab);}
  function updateControls(){const a=$('unit-a').checked,b=$('unit-b').checked;config={scope:a&&b?'both':a?'A':b?'B':'none',access:$('access').value,methods:$('methods').value};render();}
  function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('export-status').textContent=`Downloaded ${name} for the current brief.`;}
  document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{config={...presets[b.dataset.preset]};render();}));
  ['unit-a','unit-b','access','methods'].forEach(id=>$(id).addEventListener('change',updateControls));
  $('reset').addEventListener('click',()=>{config={...presets.both};groupMode='product';activeTab='reasons';$('export-status').textContent='';render();});
  $('step-range').addEventListener('input',()=>{stop();step=+$('step-range').value;selected=Math.max(0,step-1);renderScene();renderRoute();});
  $('step-back').addEventListener('click',()=>{stop();step=Math.max(0,step-1);selected=Math.max(0,step-1);renderScene();renderRoute();});
  $('step-next').addEventListener('click',()=>{stop();step=Math.min(result.actions.length,step+1);selected=Math.max(0,step-1);renderScene();renderRoute();});
  $('play').addEventListener('click',()=>{if(timer){stop();return;}if(step===result.actions.length)step=0;$('play').textContent='Pause';timer=setInterval(()=>{step++;selected=Math.max(0,step-1);renderScene();renderRoute();if(step===result.actions.length)stop();},900);});
  document.querySelectorAll('[data-tab]').forEach(b=>{b.addEventListener('click',()=>tab(b.dataset.tab));b.addEventListener('keydown',e=>{const names=['reasons','wbs','comparison','findings'];if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const index=e.key==='Home'?0:e.key==='End'?3:(names.indexOf(activeTab)+(e.key==='ArrowRight'?1:3))%4;tab(names[index],true);}});});
  $('group-product').addEventListener('click',()=>{groupMode='product';renderWBS();});$('group-trade').addEventListener('click',()=>{groupMode='trade';renderWBS();});
  document.querySelectorAll('[data-meaning-view]').forEach(b=>b.addEventListener('click',()=>{meaningView=b.dataset.meaningView;meaningSelection='';renderMeaning();}));
  $('download-domain').addEventListener('click',()=>download('direct-domain.pddl',comparison.directPDDL.domain,'text/plain'));
  $('download-problem').addEventListener('click',()=>download('tunnel-problem.pddl',comparison.directPDDL.problem,'text/plain'));
  $('download-turtle').addEventListener('click',()=>download('work-and-reasons.ttl',WorkModel.exportTurtle(config,result),'text/turtle'));
  $('download-receipt').addEventListener('click',()=>download('work-that-must-exist.json',JSON.stringify({title:'The work that must exist',foray:210,config,modelSHA256:WorkModel.model.sourceSHA256,assumptions:result.problem.assumptions,result,packaging:WorkModel.packagePlan(result,groupMode),comparison:{sameSemantics:comparison.sameSemantics,valid:comparison.valid,direct:comparison.direct},limits:'Synthetic finite model. No engineering validity or ontology superiority is established.'},null,2),'application/json'));
  $('share').addEventListener('click',async()=>{writeURL();try{await navigator.clipboard.writeText(location.href);$('export-status').textContent='Link copied with the current goals, access, methods and view.';}catch{$('export-status').textContent='Copy the address from your browser; it now contains this experiment’s settings.';}});
  addEventListener('hashchange',()=>{readURL();render();});
  try{readURL();render();}catch(error){$('result-summary').textContent='The model could not load. Please reload this page.';$('route').textContent=error.message;console.error(error);}
})();
