#!/usr/bin/env python3
"""Compile the declared RDF planning vocabulary. Requires rdflib==7.1.4.

Run: python compile_ontology.py [--check]
No OWL planning inference is claimed: lists explicitly declare preconditions,
effects and obligations; RDFS subclass paths validate foundational meanings.
The browser runs offline against the reproducible compiled artifact.
"""
from pathlib import Path
import argparse
import hashlib
import json
import re
import rdflib
from rdflib import RDF, RDFS, Namespace

HERE = Path(__file__).resolve().parent
W = Namespace("https://solway.example/work/schema#")
D = Namespace("https://solway.example/work/domain#")
F = Namespace("https://solway.example/work/foundation#")
L = Namespace("https://solway.example/work/local#")


def compile_model(path=HERE / "ontology.ttl"):
    source = path.read_text()
    graph = rdflib.Graph().parse(data=source, format="turtle")

    def one(node, pred):
        values = list(graph.objects(node, pred))
        if len(values) != 1:
            raise ValueError(f"Expected exactly one {pred} on {node}")
        return values[0]

    def seq(node, pred):
        return [str(x) for x in graph.items(one(node, pred))]

    def foundational(node):
        roots = {F.PhysicalObject, F.Process, F.Quality, F.InformationContent}
        ancestors = set(graph.transitive_objects(node, RDFS.subClassOf))
        matches = ancestors & roots
        if len(matches) != 1:
            raise ValueError(f"Ambiguous or missing foundational category: {node}")
        return str(matches.pop()).split("#")[-1]

    scenario = L.Vignette
    units = []
    for node in graph.items(one(scenario, W.units)):
        typ = one(node, RDF.type)
        if foundational(typ) != "PhysicalObject":
            raise ValueError("Local units must be physical objects")
        units.append({"id": str(one(node, W.key)), "label": str(one(node, RDFS.label)), "iri": str(node), "type": str(typ)})
    if [u["id"] for u in units] != ["a", "b"]:
        raise ValueError("This bounded vignette requires exactly local units a and b")

    profile = one(scenario, W.goalProfile)
    obligations = []
    for node in graph.items(one(profile, W.requirements)):
        meaning = one(node, W.meaning)
        obligations.append({"id": str(one(node, W.id)), "binding": str(one(node, W.binding)),
            "label": str(one(node, RDFS.label)), "meaning": str(meaning),
            "category": foundational(meaning), "source": str(node),
            "positive": seq(node, W.positive), "negative": seq(node, W.negative)})

    actions = []
    for node in sorted(graph.subjects(RDF.type, W.ActionTemplate), key=lambda n: int(one(n, W.order))):
        process_types = [t for t in graph.objects(node, RDF.type) if t != W.ActionTemplate]
        if len(process_types) != 1 or foundational(process_types[0]) != "InformationContent":
            raise ValueError("Action templates must be method specifications, not process occurrences")
        if foundational(one(node, W.describesProcess)) != "Process":
            raise ValueError("Methods must describe a process")
        action = {key: str(one(node, getattr(W, key))) for key in ("id", "binding", "method", "kind", "trade")}
        action.update({"label": str(one(node, RDFS.label)), "source": str(node), "describesProcess": str(one(node, W.describesProcess))})
        action.update({key: seq(node, getattr(W, key)) for key in ("positive", "negative", "add", "delete")})
        if set(action["positive"]) & set(action["negative"]) or set(action["add"]) & set(action["delete"]):
            raise ValueError(f"Contradictory action template: {node}")
        actions.append(action)

    policies = {str(one(n, W.key)): seq(n, W.allows) for n in graph.subjects(RDF.type, W.AccessPolicy)}
    for item in actions + obligations:
        if item["binding"] not in ("site", "unit"):
            raise ValueError("Unsupported binding")
        for key in ("positive", "negative", "add", "delete"):
            for atom in item.get(key, []):
                if not re.fullmatch(r"[a-z][a-z-]*(?:\{unit\})?[a-z-]*", atom):
                    raise ValueError(f"Invalid atom template: {atom}")
    return {"version": 1, "sourceSHA256": hashlib.sha256(source.encode()).hexdigest(),
        "sourceTurtle": source, "scenario": str(one(scenario, RDFS.label)), "units": units,
        "initialUnitFacts": seq(scenario, W.initialUnitFacts), "scopeFact": str(one(scenario, W.scopeFact)),
        "assumptions": sorted(str(x) for x in graph.objects(scenario, W.assumption)),
        "accessPolicies": policies, "obligationTemplates": obligations, "actionTemplates": actions}


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if checked-in JS differs from ontology")
    args = parser.parse_args()
    output = "// Generated by compile_ontology.py from ontology.ttl; do not edit.\n" + "globalThis.WorkModelData = " + json.dumps(compile_model(), indent=2, sort_keys=True) + ";\n"
    target = HERE / "model-data.js"
    if args.check:
        if not target.exists() or target.read_text() != output:
            raise SystemExit("model-data.js is stale; run compile_ontology.py")
        print("Ontology parses, foundational distinctions validate, and compiled data is current.")
    else:
        target.write_text(output)
        print(f"Compiled {target.name}")
